### ISSUE TITLE
Annotation Format explanation a little too short.

### ISSUE THREAD

**Issue by LetiP** [HKUST-KnowComp/Visual_PCR#2]
Hello and congratulations for this very useful dataset!

I am new to coreference resolution and perhaps the annotation format you are using is a standard one. Nevertheless, I think me and many other would profit from a longer description of the annotation format:

For example, looking at this content of "sentences":
[['A', 'firefighter', 'rests', 'his', 'arm', 'on', 'a', 'parking', 'meter', 'as', 'another', 'walks', 'past', '.'], ['Is', 'he', 'in', 'his', 'gear', '?'], ['Yes', '.'], ['Are', 'they', 'at', 'the', 'firehouse', '?'], ['No', '.'], ['Is', 'there', 'a', 'fire', 'truck', '?'], ['No', '.'], ['Has', 'he', 'been', 'fighting', 'a', 'fire', '?'], ['No', '.'], ['Has', 'he', 'been', 'working', 'an', 'accident', '?'], ['Possibly', '.'], ['Does', 'he', 'have', 'a', 'radio', '?'], ['No', '.'], ['Is', 'the', 'other', 'person', 'a', 'firefighter', 'as', 'well', '?'], ['Yes', '.'], ['Does', 'that', 'person', 'have', 'a', 'radio', '?'], ['No', '.'], ['Can', 'you', 'see', 'their', 'company', 'number', '?'], ['No', '.'], ['Do', 'they', 'have', 'on', 'their', 'helmets', '?'], ['Yes', '.']],
I understand from the annotation that the first element in the lists of lists is the caption, then the question, then the answer, and so on.

But now to the coreference annotation:
'candidate_NPs': [[0, 1], [3, 4], [6, 8], [10, 10], [12, 12]],
'correct_NPs': [[0, 1], [10, 10]]
'correct_caption_NPs': [[0, 1], [3, 4], [6, 8], [10, 10], [12, 12]]

 I do not know what these indices refer to nor what the difference between "candidate" and "correct" is. Could you please update the readme so that this becomes clearer?

Thank you!

**Comment by LetiP** [comment]
For the indices: I would assume that "candidate_NP" is a list of indices referring to "sentences", so that
[0,1] stands for "firefighter", then [3, 4] stands for "the" (which makes no sense), but then [6, 8] really makes no sense. I am very confused, sorry.

**Comment by YuCosine** [comment]
The annotation of [start, end] indicates the starting index and the ending index of the phrases following the annotaion used in previous coreference resolution works. The indices is counted by concatenating all sentences of the dialogue together. For the example you give, [0, 1] indicates the phrase of "a firefighter", [3, 4] indicates "his arms", [6, 8] indicates "a parking meter", and [10, 10] indicates "another."
"Candidate_NPs" means the noun phrases as candidates for antecedents, while "correct_caption_NPs" denotes the correct antecedents. In this example, all the noun phrases mentioned above serve as candidates of antecedents for the first "he", while only [0, 1] "a firefighter" and [10, 10] "another" are correct antecedents.

**Comment by LetiP** [comment]
Thank you! This is helpful!
