### ISSUE TITLE
Documentation falls short.

### ISSUE THREAD

**Issue by LetiP** [HKUST-KnowComp/Visual_PCR#3]
Hello,
congrats for your nice work on a valuable dataset!
I am writing again an issue to point out that the data annotation format is not documented comprehensively. Previously I was confused about the pronoun annotation; confusion that would not have arisen if there would have been a sentence stating how the pronouns are annotated (with start and end indexes on the whole dialog input).

Now I am writing to you to ask: What does the "doc_key" contain in the jsonlines files? I am wondering, especially because these "doc_key"s contain values like "dl:train_42" in the test set of vispro. Where does train vs test originate from in the "doc_key" and what do the numbers mean?

I would be happy with a response here on the issue. I also would like to point out, that you could encourage more people to work with your dataset, if you would add comment lines in https://github.com/HKUST-KnowComp/Visual_PCR#annotation-format explaining what each key means and what it contains.

Thank you in advance!
Leti

**Comment by YuCosine** [comment]
Hi,
Thanks for your advice.
I have updated the README regarding your concerns.
If you have further questions, please let me know.

**Comment by LetiP** [comment]
Thank you, now it is much clearer as I (and also others) can find this information! :)
