### ISSUE TITLE
End-to-End + Visual baseline

### ISSUE THREAD

**Issue by canuck89** [HKUST-KnowComp/Visual_PCR#4]
Hi, great work guys! I just had a few questions regarding the **end-to-end + visual baseline**. Could you please explain what features were extracted from images? And, were these visual features concatenated with each potential span before training? 

Is there any code that we can look for the **end-to-end + visual baseline** model? Thank you!

**Comment by YuCosine** [comment]
Hi, I have uploaded code for the end-to-end + visual baseline.

Before training the coreference model, we extract the output of average pooling layer of ResNet-152 from images as visual features. The features are fixed and concatenated to each (candidate, pronoun) pair during training.

To reproduce, first download images from [VisDial](https://visualdialog.org/data) to `data` folder, then run `python get_im_fc.py`  to get image features.

Then run `python train.py e2e_visual_baseline`.
